version: '2'

services:
    conference_web:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: src/ConferenceWeb/
        ports:
            - 8080:8080
        volumes:
            - .:/opt
        depends_on:
            - conference_management
            - rabbitmq
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=conference_web"
            DB_PATH: /opt/var/db/conference_web
        restart: "on-failure:5"

    conference_management:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: src/ConferenceManagement/
        ports:
            - 8083:8080
        volumes:
            - .:/opt
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=conference_management"
            DB_PATH: /opt/var/db/conference_management
        restart: "on-failure:5"

    orders_and_registrations:
        image: matthiasnoback/php_workshop_tools_base
        command: php src/OrdersAndRegistrations/consume.php
        volumes:
            - .:/opt
        depends_on:
            - rabbitmq
            - mailcatcher
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=orders_and_registrations"
            DB_PATH: /opt/var/db/orders_and_registrations
        restart: "on-failure:5"

    orders_and_registrations_web:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: src/OrdersAndRegistrations/
        volumes:
            - .:/opt
        depends_on:
            - rabbitmq
        ports:
            - 8081:8080
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=orders_and_registrations_web"
            DB_PATH: /opt/var/db/orders_and_registrations
        restart: "on-failure:5"

    external_payment_provider:
        image: matthiasnoback/php_workshop_tools_simple_webserver
        command: src/ExternalPaymentProvider/
        volumes:
            - .:/opt
        ports:
            - 8082:8080
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
            PHP_IDE_CONFIG: "serverName=external_payment_provider"
            DB_PATH: /opt/var/db/external_payment_provider
        restart: "on-failure:5"

    redis:
        image: redis:3.2
        volumes:
            - ./var/redis:/data
        command: redis-server --appendonly yes

    redis_browser:
        image: inventid/redis-browser
        ports:
            - 8079:4567
        volumes:
            - ./docker/redis-browser/config:/opt/config

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        restart: "on-failure:5"

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
        restart: "on-failure:5"

    devtools:
        image: matthiasnoback/php_workshop_tools_base
        user: $HOST_UID:$HOST_GID
        environment:
            COMPOSER_HOME: "/home/.composer"
        volumes:
            - ${PWD}:/opt
            - ${COMPOSER_HOME}:/home/.composer
        restart: "no"
